import json
from io import BytesIO
from datetime import datetime
from fpdf import FPDF
from .helpers import risk_band


BRAND = (14, 165, 164)
INK = (15, 23, 42)
MUTED = (100, 116, 139)
LIGHT = (241, 245, 249)
DANGER = (220, 38, 38)
OK = (16, 185, 129)


class MedicalReportPDF(FPDF):
    def __init__(self, patient, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.patient = patient
        self.set_auto_page_break(auto=True, margin=18)
        self.set_margins(15, 15, 15)

    def header(self):
        self.set_fill_color(*BRAND)
        self.rect(0, 0, 210, 28, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 18)
        self.set_xy(15, 7)
        self.cell(0, 8, "MEDICARE AI HOSPITAL", ln=1)
        self.set_font("Helvetica", "", 9)
        self.set_x(15)
        self.cell(0, 5, "AI-Powered Multi-Disease Diagnostic Center", ln=1)
        self.set_x(15)
        self.cell(0, 5, "College Road, 56000 Gojra, District Toba Tek Singh, Punjab", ln=1)

        self.set_xy(150, 8)
        self.set_font("Helvetica", "B", 11)
        self.cell(45, 5, "MEDICAL REPORT", align="R", ln=1)
        self.set_xy(150, 13)
        self.set_font("Helvetica", "", 8)
        self.cell(45, 4, datetime.now().strftime("%d %b %Y, %I:%M %p"), align="R", ln=1)
        self.set_xy(150, 17)
        self.cell(45, 4, f"Report ID: MR-{self.patient['id']:05d}-{datetime.now().strftime('%y%m%d')}", align="R", ln=1)

        self.set_text_color(*INK)
        self.ln(16)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*MUTED)
        self.cell(0, 5, "This report is generated by an AI diagnostic support system. It does not replace a certified medical examination.", align="C", ln=1)
        self.set_font("Helvetica", "", 8)
        self.cell(0, 4, f"Page {self.page_no()} of {{nb}}   |   MediCare AI - Confidential Patient Report", align="C")

    def section_title(self, title):
        self.set_fill_color(*LIGHT)
        self.set_text_color(*BRAND)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 8, "  " + title.upper(), ln=1, fill=True)
        self.set_text_color(*INK)
        self.ln(2)

    def kv_row(self, key, value, bold_value=False):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*MUTED)
        self.cell(45, 6, key)
        self.set_text_color(*INK)
        if bold_value:
            self.set_font("Helvetica", "B", 9)
        self.cell(0, 6, str(value), ln=1)

    def patient_info(self):
        self.section_title("Patient Information")
        p = self.patient
        col_w = 90
        rows = [
            ("Patient Name", p.get("full_name", "-")),
            ("Patient ID", f"MC-{p['id']:05d}"),
            ("Age / Gender", f"{p.get('age', '-')} years / {p.get('gender', '-')}"),
            ("Blood Group", p.get("blood_group", "-") or "-"),
            ("Email", p.get("email", "-")),
            ("Contact", p.get("contact", "-") or "-"),
        ]
        y0 = self.get_y()
        for i, (k, v) in enumerate(rows):
            x = 15 + (col_w * (i % 2))
            y = y0 + (i // 2) * 7
            self.set_xy(x, y)
            self.set_font("Helvetica", "", 9)
            self.set_text_color(*MUTED)
            self.cell(35, 6, k + ":")
            self.set_text_color(*INK)
            self.set_font("Helvetica", "B", 9)
            self.cell(col_w - 35, 6, str(v))
        self.set_y(y0 + ((len(rows) + 1) // 2) * 7 + 3)
        self.ln(2)

    def prediction_block(self, pred):
        disease = pred["disease"]
        prob = pred["probability"]
        result = pred["result"]
        band, _ = risk_band(prob)
        is_pos = result == "Positive"

        self.section_title(f"{disease} Diagnostic Assessment")

        self.set_font("Helvetica", "", 9)
        self.set_text_color(*MUTED)
        self.cell(45, 6, "Test Date:")
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*INK)
        self.cell(0, 6, datetime.fromisoformat(pred["created_at"]).strftime("%d %B %Y, %I:%M %p"), ln=1)

        self.set_font("Helvetica", "", 9)
        self.set_text_color(*MUTED)
        self.cell(45, 6, "Examination Type:")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*INK)
        self.cell(0, 6, "AI-Powered Machine Learning Prediction", ln=1)

        self.ln(2)
        bar_y = self.get_y()
        if is_pos:
            self.set_fill_color(*DANGER)
        else:
            self.set_fill_color(*OK)
        self.rect(15, bar_y, 180, 18, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 12)
        self.set_xy(20, bar_y + 2)
        self.cell(120, 6, f"RESULT: {result.upper()}", ln=1)
        self.set_font("Helvetica", "", 9)
        self.set_xy(20, bar_y + 9)
        self.cell(120, 6, f"AI Risk Probability: {prob*100:.2f}% - {band}", ln=1)

        self.set_xy(140, bar_y + 4)
        self.set_font("Helvetica", "B", 22)
        self.cell(50, 10, f"{prob*100:.0f}%", align="R", ln=1)

        self.set_text_color(*INK)
        self.set_y(bar_y + 21)
        self.ln(2)

        try:
            inputs = json.loads(pred["inputs_json"])
        except Exception:
            inputs = {}

        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*INK)
        self.cell(0, 6, "Clinical Parameters Submitted:", ln=1)

        self.set_fill_color(*LIGHT)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*BRAND)
        self.cell(95, 7, " Parameter", border=0, fill=True)
        self.cell(85, 7, " Value", border=0, fill=True, ln=1)
        self.set_text_color(*INK)
        self.set_font("Helvetica", "", 9)

        for i, (k, v) in enumerate(inputs.items()):
            if i % 2 == 0:
                self.set_fill_color(255, 255, 255)
            else:
                self.set_fill_color(248, 250, 252)
            display_value = f"{v:.4f}" if isinstance(v, float) and abs(v) < 1 else (
                f"{v:.2f}" if isinstance(v, float) else str(v)
            )
            self.cell(95, 6, " " + k.replace("_", " "), border=0, fill=True)
            self.cell(85, 6, " " + display_value, border=0, fill=True, ln=1)

        self.ln(3)

        self.set_font("Helvetica", "B", 10)
        self.cell(0, 6, "Clinical Interpretation & Advice:", ln=1)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*INK)
        advice = pred.get("advice") or ""
        if not advice:
            advice = ("The model indicates an elevated risk profile based on the submitted parameters."
                      if is_pos else
                      "The model indicates a low risk profile based on the submitted parameters.")
        if prob >= 0.8:
            advice = advice + " Please consult a qualified physician immediately for confirmatory testing."
        elif prob >= 0.5:
            advice = advice + " Schedule a clinical consultation within the next 1-2 weeks."
        elif prob >= 0.3:
            advice = "Borderline indicators detected. Maintain a healthy lifestyle and re-test in 3 months. " + advice
        self.multi_cell(0, 5, advice)
        self.ln(3)

    def recovery_section(self, latest, previous):
        self.section_title(f"{latest['disease']} Recovery Comparison")
        self.set_font("Helvetica", "", 9)
        change = (latest["probability"] - previous["probability"]) * 100
        if change < -5:
            verdict = "IMPROVING - Risk has decreased significantly compared to your previous checkup."
            color = OK
        elif change > 5:
            verdict = "WORSENING - Risk has increased compared to your previous checkup. Clinical follow-up is advised."
            color = DANGER
        else:
            verdict = "STABLE - Risk levels remain comparable to your previous checkup."
            color = (100, 116, 139)
        self.set_text_color(*color)
        self.set_font("Helvetica", "B", 10)
        self.cell(0, 6, verdict, ln=1)
        self.set_text_color(*INK)
        self.set_font("Helvetica", "", 9)
        self.cell(0, 5, f"Previous Risk ({datetime.fromisoformat(previous['created_at']).strftime('%d %b %Y')}): {previous['probability']*100:.2f}%", ln=1)
        self.cell(0, 5, f"Latest Risk ({datetime.fromisoformat(latest['created_at']).strftime('%d %b %Y')}): {latest['probability']*100:.2f}%", ln=1)
        self.cell(0, 5, f"Change: {change:+.2f} percentage points", ln=1)
        self.ln(3)


def generate_report(patient, predictions, include_recovery_pairs=None) -> bytes:
    pdf = MedicalReportPDF(patient)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.patient_info()

    for pred in predictions:
        pdf.prediction_block(pred)

    if include_recovery_pairs:
        for latest, previous in include_recovery_pairs:
            pdf.recovery_section(latest, previous)

    out = pdf.output(dest="S")
    if isinstance(out, str):
        return out.encode("latin-1")
    return bytes(out)
